name: Build targets on release
on:
  release:
    types: [created]
jobs:
  release:
    name: Publish for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            path: ./build/linux/releaseExecutable/kotlin-native-playground.kexe
            asset_name: hello-linux-amd64
          - os: windows-latest
            path: .\build\windows\releaseExecutable\kotlin-native-playground.exe
            asset_name: hello-windows-amd64
          - os: macos-latest
            path: ./build/macos/releaseExecutable/kotlin-native-playground.kexe
            asset_name: hello-macos-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.path }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}